name: Update DB

permissions: 
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "* 3 * * *" # Runs at 03:00 UTC daily

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests nltk rake_nltk beartype
      - name: Run Python script
        run: python3 scripts/update_db.py "data/projects.json"
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions-update_db[bot]"
          git config user.email "github-actions-update_db[bot]@users.noreply.github.com"
          git add "data/projects.json"
          git commit -m "data: Update DB"
          git push