name: Update requirements.txt

permissions:
  contents: write

on:
  push:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run Python script
        run: python3 backend/convert_toml_to_requirements.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions-update_db[bot]"
          git config user.email "github-actions-update_db[bot]@users.noreply.github.com"
          git add "requirements.txt"
          git commit -m "build: Update requirements.txt"
          git push